# Generated by Django 3.2.8 on 2021-10-23 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('l', 'litres'), ('-', 'units')], default='-', max_length=3)),
                ('in_stock', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0.01)])),
            ],
        ),
    ]
