# Generated by Django 3.2.8 on 2021-10-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchase_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='menuItem',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='total',
        ),
    ]
