# Generated by Django 3.2.8 on 2021-10-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211029_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
            preserve_default=False,
        ),
    ]
