# Generated by Django 3.2.8 on 2021-10-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchase_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-time', 'menu_item']},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='income',
            new_name='profit',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of', to='inventory.ingredient'),
        ),
    ]
