# Generated by Django 3.2.8 on 2021-11-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211031_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'kilograms'), ('g', 'grams'), ('l', 'litres'), ('ml', 'millilitres'), ('oz', 'ounces'), ('lb', 'pounds'), ('gal', 'gallons'), ('pkt', 'packets'), ('-', 'units')], default='-', max_length=3),
        ),
    ]
